default_platform(:ios)

platform :ios do
  lane :beta do
    get_certificates
    get_provisioning_profile
    build_app(
      scheme: "Castle",
      workspace: "ios/Castle.xcworkspace"
    )
    # upload_to_testflight
  end
end
