default_platform(:ios)

def set_bundle_version_from_commit_count
  bundle_version = Actions.lane_context[SharedValues::VERSION_NUMBER] + ".1" + number_of_commits.to_s  
  puts "Setting build number to '" + bundle_version + "'..."
  set_info_plist_value(
    path: "./ios/Castle/Info.plist",
    key: "CFBundleVersion",
    value: bundle_version
  )
end

platform :ios do
  before_all do
    setup_circle_ci
    Actions.lane_context[SharedValues::VERSION_NUMBER] = get_version_number(
      xcodeproj: "./ios/Castle.xcodeproj",
      target: "Castle"
    )
    set_bundle_version_from_commit_count
  end
  lane :beta do
    get_certificates(
        username: "services@castle.games"
    )
    get_provisioning_profile(
        username: "services@castle.games"
    )
    build_app(
      scheme: "Castle",
      workspace: "ios/Castle.xcworkspace"
    )
    upload_to_testflight(
        username: "services@castle.games"
    )
  end
end
