platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

inhibit_all_warnings!

target 'Castle' do
  # Pods for Castle
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # Native modules
  pod 'RNBootSplash', :path => '../node_modules/react-native-bootsplash'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # Explicitly provide rn-video in order to get caching subspec
  pod 'react-native-video', :path => '../node_modules/react-native-video', :subspecs => ['Video', 'VideoCaching']
  
  use_native_modules!
  use_unimodules!
end
