platform :ios, '12.1'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

inhibit_all_warnings!

target 'Castle' do
  # Pods for Castle
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Native modules
  pod 'RNBootSplash', :path => '../node_modules/react-native-bootsplash'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # Explicitly provide rn-video in order to get caching subspec
  pod 'react-native-video', :path => '../node_modules/react-native-video', :subspecs => ['Video', 'VideoCaching']

  # use Adjust standard iOS package rather than adjust-react-native
  # because we need native integration on android
  pod 'Adjust', '~> 4.29.2'
  
  use_native_modules!
end

post_install do |installer|
  react_native_post_install(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET' # inherit
    end
  end
end
