jobs:
  build_beta_ios:
    macos:
      xcode: "11.2.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "mobile/Gemfile.lock" }}
      - run:
          name: bundle install
          command: |
              pushd mobile
              bundle check || bundle install --path vendor/bundle
              popd
      - save_cache:
          key: 1-gems-{{ checksum "mobile/Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Build and upload
          command: cd mobile && ./tools/upload-beta-build.sh
      - store_artifacts:
          path: output

  build_beta_android:
    docker:
      - image: 'reactnativecommunity/react-native-android:5.1'
    resource_class: xlarge
    steps:
      - checkout:
      - run:
          name: Submodules
          command: git submodule update --init --recursive
      - restore_cache:
          key: dependency-cache-{{ checksum "mobile/package-lock.json" }}
      - run:
          name: Install Dependencies
          command: cd mobile && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "mobile/package-lock.json" }}
          paths:
            - ./mobile/node_modules
      - run:
          name: Build
          command: cd mobile && /bin/bash tools/build-android-beta.sh
          no_output_timeout: 30m

workflows:
  version: 2
  build:
    jobs:
      - build_beta_ios:
          filters:
            branches:
              only:
                - beta/ios
  build_beta_android:
    jobs:
      - build_beta_android:
          filters:
            branches:
              only:
                - android_ci_test
