name: core clang-tidy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout-and-run-clang-tidy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Run clang-tidy
      uses: castle-xyz/action-clang-tidy@6df533bcb95cf95c6588d40f05ed4e6abd86df66
      with:
        scandir: './core'
        builddir: 'build'
        excludedirs: 'vendor'
        extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
        cmakeoptions: ''
